version: '3'
services:
  web:
    build: .
    ports:
     - "5000:5000"
    volumes:
     - .:/code
    environment:
      MYENV: "This is one to there"
    networks:
      - demo
  redis:
    image: "redis:alpine"
    networks:
      - demo
networks:
  demo:
    driver: bridge

